### PR TITLE
Add a RoboVikes Profile settings

### PR DESCRIPTION
**Pull request by duane701**
RoboVikes follow a C++ style defined by RoboVikesProfile.xml.

Update the README with instructions for using the profile.
Update the README to follow markdown syntax.

@Diego-Andrade

### CODE REVIEW

**Comment by Diego-Andrade** [comment]
This will address the issue of tabs and soaces correct?

**Comment by duane701** [comment]
> This will address the issue of tabs and soaces correct?

Yes, it will. A few other minor changes as well involving indenting.

**Comment by Diego-Andrade** [comment]
Also is in environment specific or can the profile be applied to just a project?

**Comment by duane701** [comment]
> Also is in environment specific or can the profile be applied to just a project?

I think it can be applied to a project rather than to all of eclipse. I think you use Project specific settings.

**Comment by duane701** [comment]
Merging in @Diego-Andrade absence.

**Pull request merged**
